apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: console:dev
spec:
  project: default
  source:
    repoURL: https://github.com/agrigorev94/kargo-demo.git
    targetRevision: main
    path: gitops/envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: console-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
