apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://registry.registry.svc.cluster.local:5000/charts/console
    path: .
    targetRevision: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: console-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
