apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: console-uz
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: console:uz
spec:
  project: default
  sources:
    - repoURL: oci://registry.registry.svc.cluster.local:5000/charts/console
      path: .
      targetRevision: 1.2.0
      helm:
        valueFiles:
          - $values/gitops/values/console-uz.yaml
    - repoURL: https://github.com/agrigorev94/kargo-demo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: console-uz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
